DROP TABLE IF EXISTS Clinic.Prescription;
DROP TABLE IF EXISTS Clinic.Diagnosis;
DROP TABLE IF EXISTS Clinic.Medication;
DROP TABLE IF EXISTS Clinic.ClinicVisit;
DROP TABLE IF EXISTS Clinic.SubstanceUse;
DROP TABLE IF EXISTS Clinic.Clinician;
DROP TABLE IF EXISTS Clinic.VillageSite;
DROP TABLE IF EXISTS Clinic.Clinic;
DROP TABLE IF EXISTS [Subject].Residence;
DROP TABLE IF EXISTS [Subject].Marriage;
DROP TABLE IF EXISTS [Subject].[SubjectName];
DROP TABLE IF EXISTS [Subject].[Name];
DROP TABLE IF EXISTS [Subject].Village;
DROP TABLE IF EXISTS [Subject].[Subject];
DROP TABLE IF EXISTS [Subject].EthnicGroup
DROP TABLE IF EXISTS [Subject].DOBSource;
